# Generated by Django 2.2 on 2019-05-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitt_id', models.IntegerField(db_index=True)),
                ('para_id', models.IntegerField(db_index=True)),
                ('para_first', models.BooleanField()),
                ('non_verse', models.BooleanField()),
                ('line_id', models.IntegerField(db_index=True)),
                ('half_line', models.CharField(max_length=1)),
                ('token_offset', models.IntegerField()),
                ('caesura_code', models.CharField(max_length=1)),
                ('pre_punc', models.CharField(max_length=2)),
                ('text', models.CharField(max_length=16)),
                ('post_punc', models.CharField(max_length=11)),
                ('syntax', models.CharField(max_length=3)),
                ('parse', models.CharField(max_length=6)),
                ('lemma', models.CharField(db_index=True, max_length=17)),
                ('pos', models.CharField(max_length=2)),
                ('o', models.CharField(max_length=2)),
                ('gloss', models.CharField(max_length=44)),
                ('with_length', models.CharField(max_length=66)),
            ],
        ),
    ]
