# Generated by Django 2.2 on 2019-05-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readbeowulf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitt_id', models.IntegerField(db_index=True)),
                ('line_id', models.IntegerField(db_index=True)),
                ('half_line', models.CharField(max_length=1)),
                ('audio_url', models.CharField(max_length=100)),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
            ],
        ),
    ]
